name: my_best_ramadhan_app
description: A Ramadhan progress tracking app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # Firebase
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.4
  cloud_firestore: ^5.6.2
  firebase_analytics: ^11.4.1
  google_sign_in: ^6.2.1
  
  # State Management
  provider: ^6.1.1
  
  # Notifications - GANTI KE AWESOME NOTIFICATIONS
  # awesome_notifications: ^0.9.3
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # UI & UX
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.4
  intl: ^0.19.0
  flutter_slidable: ^3.0.1
  
  # Utilities
  url_launcher: ^6.2.4
  flutter_local_notifications: ^20.0.0
  timezone: ^0.10.1
  flutter_timezone: ^5.0.1
  permission_handler: ^12.0.1
  app_settings: ^7.0.0
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo_inner_light.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/