name: my_best_ramadhan_app
description: A Ramadhan progress tracking app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # Firebase
  firebase_core: ^2.25.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.15.0
  
  # State Management
  provider: ^6.1.1
  
  # Notifications - GANTI KE AWESOME NOTIFICATIONS
  # awesome_notifications: ^0.9.3
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # UI & UX
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.4
  intl: ^0.19.0
  
  # Utilities
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  # Uncomment setelah kamu punya asset
  # assets:
  #   - assets/images/
  #   - assets/fonts/